### ISSUE TITLE
Produce a more meaningful error code on `AutomationRemoteOperationStatus::InstructionLimitExceeded`

### ISSUE THREAD

**Issue by beweedon** [microsoft/Microsoft-UI-UIAutomation#87]
UIA returns `AutomationRemoteOperationStatus::InstructionLimitExceeded` when the number of instructions executed in the remote process exceeds 10000. However, currently the wrapper just transforms this into `E_FAIL` in `AutomationRemoteOperationResultSet::OperationStatus`. In `UiaOperationScope::Resolve`, this `E_FAIL` is plumbed through to the client.

We should provide a way to determine whether the remote operation exited with `InstructionLimitExceeded`. I'm listing three potential ways here, although more are certainly possible:

- Create a custom HRESULT using the [customer bit](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/0642cb2f-2075-4469-918c-4441e69c548a) and return this instead of `E_FAIL`.
- Create a custom exception which `UiaOperationScope::Resolve` throws on `InstructionLimitExceeded`.
- Add support to `AutomationRemoteOperationResultSet` to return whether `InstructionLimitExceeded` occurred, and provide an alternative to `UiaOperationScope::Resolve` which returns an `AutomationRemoteOperationResultSet`.

**Comment by beweedon** [comment]
@michaelDCurran @zhayuli

**Comment by michaelDCurran** [comment]
I personally like option 2: a custom exception thrown by UiaOperationScope::Resolve when InstructionLimitExceeded.
It would also be good if UiaOperationScope::ResolveHrInternal can resolve (bring back) values even for InstructionLimitExceeded. Currently it only does this if execute returns a success code. 
In other words, any values calculated before the limit was hit, should be available to the client at the end.
This is necessary so that client code can make use of work already executed, E.g. for logging progress messages for tracing, or for knowing where to restart an algorithm from where it left off.

**Comment by ggordon-vispero** [comment]
I like the idea of the first two options combined: return a custom HRESULT and have the UIA Operations abstraction throw a custom exception.

**Comment by beweedon** [comment]
@ggordon-vispero, to clarify, do you mean to create a custom HRESULT and throw that HRESULT using [winrt::throw_hresult](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/error-handling/throw-hresult) or WIL's `THROW_HR`; or to create a custom HRESULT and throw a completely custom `std::exception`?

I think a fully custom exception type would cause issues for Narrator, but I'm not sure what exception models you all are using.

**Comment by ggordon-vispero** [comment]
winrt::throw_hresult or WIL's THROW_HR would work fine for us.
